### ISSUE TITLE
allow only one vote for MCSR

### ISSUE THREAD

**Issue by isaacdontjelindell** [LutherSrProject/TapVote#132]
Need to figure out a way to send the proper `/deVote` call when the client user changes their vote in an MCSR question.

Right now, when they change which answer is selected, a new vote is added, but the old one also remains in the database.

I think this is going to involve keeping track of the previous vote, and when changes, issuing a `/deVote` call before the new `/vote` call.

**Comment by etingel** [comment]
With a MCSR question, a client would likely use radio buttons*. Once the first button is clicked, it sends the vote and stores in RAM what answerId was sent. When they change their answer, the client will first send a deVote with the stored answerId followed by a vote with the new answerId. As before, this gets stored.

For MCMR, checkboxes\* would likely be used. When a box is checked and the client knows that it still has responses remaining, send a vote for that answerId. When they run out of responses, display an error. The same error checking will eventually be done on the server-side once sessions are in place. When a box is unchecked, send a deVote.

*Note: actual client elements like these do not have to actually look like checkboxes or radio buttons, just function like them.

**Comment by isaacdontjelindell** [comment]
This is implemented by pull request #133.
