### ISSUE TITLE
Create survey user-flow

### ISSUE THREAD

**Issue by isaacdontjelindell** [LutherSrProject/TapVote#152]
This is for _after_ demo day.

What should happen when a user clicks the "Create Survey" button in `createsurvey.html`?

Right now, it just shows the two links (to results and to take the survey). If those links are clicked, the corresponding page opens in a new tab, but the new survey form is still there and filled in. 

There are a few options, some if which will depend on how we do user stuff.
- If we have a way of temporarily remembering that this user was the user that created the survey, we could redirect them directly to the admin or to the takesurvey page, while also presenting an option to show the URLs they will need.
- We could keep it basically as it is, but remove the new-survey form once the survey has actually been created. Maybe it could just show the questions that are part of the new survey, without showing them as a form?

**Comment by etingel** [comment]
Neither, because there should be no create survey button.

**Comment by isaacdontjelindell** [comment]
Let's redirect to EditSurvey
