### ISSUE TITLE
Multiple choice, multiple response

### ISSUE THREAD

**Issue by isaacdontjelindell** [LutherSrProject/TapVote#79]
Allow creation of a multiple choice question that allows the user to select multiple responses (MCMR).

This will require DB and API work to handle removal, replacement of answers.

**Comment by etingel** [comment]
When user stuff is added, database should not allow more than one vote by a user for a single answer (unless that becomes a new question type).

**Comment by isaacdontjelindell** [comment]
That will be a validation case on the DB side. Client side won't allow it.
