### ISSUE TITLE
Session Support

### ISSUE THREAD

**Issue by isaacdontjelindell** [LutherSrProject/TapVote#86]
- Only allow user to take a survey once. (They can, however, change their answer all the way up to the end date - #84).
- only survey creator can edit survey

**Comment by etingel** [comment]
By following the steps here:
https://github.com/jebas/connect-pg

sudo apt-get install pgtap
sudo -u postgres psql -d tapvote
CREATE EXTENSION pgtap;
npm install
sudo -u postgres psql -d tapvote -f ./node_modules/connect-pg/lib/session_install.sql
sudo -u postgres psql -d tapvote -c 'select correct_web()'

To change nodepg's password:
sudo -u postgres psql -d tapvote -c "alter user nodepg with password 'wearetapvote'"

Recommend using environmental vars TAPVOTE_DATABASE_SESSION_USER and TAPVOTE_DATABASE_SESSION_PASSWORD to use the nodepg account, which has minimal permissions.
