### ISSUE TITLE
API: removeQuestion

### ISSUE THREAD

**Issue by isaacdontjelindell** [LutherSrProject/TapVote#89]
Given a questionId, remove it from the database.

`{questionId: 5}`

**Comment by isaacdontjelindell** [comment]
@etingel I know we discussed it, but this should take multiple questions, right? (and be called removeQuestions)

I'm thinking something like `{questionIds: [2, 4, 6, 8]}`

**Comment by etingel** [comment]
Hmm.... We only discussed addQuestions.

I don't know what to think, here. Unlike in the add case, it's possible for this to fail part way through due to permissions problems or non-existence of ids. Therefore, if it's done this way, it should probably use database transactions so that the whole thing can be rolled back if any of the questions fail to delete.

**Comment by isaacdontjelindell** [comment]
Or perhaps it should just be best effort (i.e. only delete the questions that actually exist). The end result is the same: if the client asks to delete non-existent question id 23, the end result is that 23 will be gone, whether it was there in the first place or not.

**Comment by etingel** [comment]
So what if 23 exists, but they aren't allowed to delete it?

**Comment by isaacdontjelindell** [comment]
hmm. What if we require the client to specify the surveyId? Then we check if they have permissions for the survey, and that all the questions belong to that survey.

**Comment by etingel** [comment]
Probably a good optional parameter (just like I'm pushing for surveyId to be an optional additional parameter on other API calls), but that still doesn't solve the issue. You're basically just saying that we should attempt removing them all at once and rollback if any of them fail, which was what I suggested.

**Comment by isaacdontjelindell** [comment]
I think permissions need to be checked at the API level rather than the DB level.

As far as this method, I'm just going to write it so it only takes one question rather than multiple. Deleting questions from a survey would be a one-at-a-time operation anyway from the client perspective.

**Comment by etingel** [comment]
Probably a good idea. We should create a new module to act as a layer between dumb database calls and the API (which is only concerned with the call being well-formed).
